- name: Ensure dotdeb debian key
  apt_key: url=http://www.dotdeb.org/dotdeb.gpg state=present
- name: Ensure dotdeb sources.lists
  template: src=dotdeb.list dest=/etc/apt/sources.list.d/dotdeb.list
  register: dotdeb_sourcelist
  when: ansible_distribution_release == "wheezy"
- name: Disable dotdeb for jessie
  file: path=/etc/apt/sources.list.d/dotdeb.list state=absent
  when: ansible_distribution_release == "jessie"
  register: dotdeb_sourcelist
- name: apt-update
  shell: apt-get update
  when: dotdeb_sourcelist.changed
- name: Install required packages
  apt: pkg={{ item }} state=latest
  with_items:
    - apache2-mpm-worker
- include: php5.yml
  when: php5 is defined and php5
