- name: Install required packages
  apt: pkg={{ item }} state=latest
  with_items:
    - apache2-mpm-worker
    - php5-fpm
    - libapache2-mod-fastcgi
    - php5-cli
    - php5-mysql
    - php5-intl
    - php5-gd
    - php5-imagick
- name: Ensure required apache2 modules
  shell: creates=/etc/apache2/mods-enabled/{{ item }}.load a2enmod {{ item }}
  with_items:
    - actions
    - fastcgi
  notify: apache2-restart
- name: Ensure php5-fpm pool
  template: src=php5-fpm-pool.conf.j2 dest=/etc/php5/fpm/pool.d/{{ fpm_pool_name }}.conf mode=0644 owner=root group=root
  notify: php5-fpm-restart
- name: Ensure required apache-fpm configuration
  template: src=php5-fpm-apache.conf.j2 dest=/etc/apache2/conf.d/php-fpm.conf mode=0644 owner=root group=root
  notify: apache2-restart
- name: php.ini
  template: src=php.ini.j2 dest=/etc/php5/fpm/php.ini owner=root group=root mode=0644
  notify: php5-fpm-restart
- name: Ensure php_secure_info
  template: src=phpinfo.php dest=/var/www/php_secure_info.php owner=root group=root mode=0644
